spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:8889/animals
    username: root
    password: qaz
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080